version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DB_HOST=db
      - DB_PORT=1433
      - DB_USERNAME=sa
      - DB_PASSWORD=YourStrong@Passw0rd
      - DB_DATABASE=DbSolicitudEfectivo
      - JWT_SECRET=your-super-secret-jwt-key-change-in-production
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - app-network

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong@Passw0rd
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
    restart: unless-stopped
    networks:
      - app-network

volumes:
  mssql_data:

networks:
  app-network:
    driver: bridge 