export class CashRequestWrite {
  constructor(
    public readonly id: number,
    public readonly fechacreada: Date,
    public readonly solicitada_porid: number,
    public readonly monto_solicitado: number,
    public readonly solicitud_tipo: number,
    public readonly solicitud_status: number,
    public readonly divicionid: number,
    public readonly tipo_pago: number,
    public readonly produccion: number,
    public readonly autorizado_porid?: number,
    public readonly fecha_requerida?: Date,
    public readonly departamento?: string,
    public readonly concepto?: string,
    public readonly fecha_orden_prod?: Date,
    public readonly num_orden_prod?: string,
    public readonly num_ticket_prod?: string,
    public readonly nombre_cliente?: string,
    public readonly solicitud_numero?: string,
    public readonly fecha_rechazada?: Date,
    public readonly razon_rechazon?: string,
    public readonly usuarionombre?: string,
    public readonly autorizadopor_nombre?: string,
    public readonly cedula?: string,
    public readonly division_nombre?: string,
    public readonly estatus_desc?: string,
    public readonly estatus_icon?: string,
    public readonly solicitud_tipo_desc?: string,
    public readonly tipo_pago_desc?: string,
    public readonly verificadopor_nombre?: string
  ) {}
} 